In [3]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
import ast
from collections import Counter

In [5]:
df = pd.read_csv("data/ML - Curricular Analytics - PIDM ONLY & Fixed Repeat IND.csv")
parsed = pd.read_csv("data/full_set.csv")

C:\Users\artkr\AppData\Local\Temp\ipykernel_29536\1496532081.py:1: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/ML - Curricular Analytics - PIDM ONLY & Fixed Repeat IND.csv")

In [6]:
parsed.head(5)

,Pidm,Semester,Admit_Level,Admit_College,Lastest_Major,Trump_Race,Trump_Race_Desc,MULTI,Race,NEW_ETHNICITY,...,SAT-ERW,SATM,SAT_TOTAL,Final GPA,Semester GPA,Semester Grades,Semester Points,Classes,CRN,Converted_SAT
0,794,201508,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,4.0,"['A+', 'A+', 'A+']","[4.0, 4.0, 4.0]","['NUR3805', 'NUR3078', 'NUR4895']","[83267.0, 89943.0, 94441.0]",1210.0
1,794,201601,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,4.0,"['A+', 'A+']","[4.0, 4.0]","['NUR4828C', 'NUR4128']","[22277.0, 22671.0]",1210.0
2,794,201605,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,4.0,"['A+', 'A+']","[4.0, 4.0]","['NUR4169C', 'NUR4795']","[55333.0, 56745.0]",1210.0
3,794,201608,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,4.0,"['A+', 'A+']","[4.0, 4.0]","['NUR4069', 'NSP4614']","[89488.0, 94546.0]",1210.0
4,794,201701,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,4.0,"['A+', 'A+']","[4.0, 4.0]","['NUR4634C', 'NSP4886']","[22741.0, 24245.0]",1210.0

In [8]:
display(df[df["Pidm"] == 794])
display(parsed[parsed["Pidm"] == 794])

,Pidm,Admit_Code,Admit_Desc,Admit_Term,Admit_Level,Admit_College,Admit_Major_Code,Major_Desc,Trump_Race,Trump_Race_Desc,...,EACT,SAT-ERW,SATM,SAT_TOTAL,Term,CRN,SUBJ,CRSE_NUMB,REPEAT_IND,FINAL_GRADE
15,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,201508.0,83267.0,NUR,3805,NaN,A+
16,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,201508.0,89943.0,NUR,3078,NaN,A+
17,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,201508.0,94441.0,NUR,4895,NaN,A+
18,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,201601.0,22277.0,NUR,4828C,NaN,A+
19,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,201601.0,22671.0,NUR,4128,NaN,A+
20,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,201605.0,55333.0,NUR,4169C,NaN,A+
21,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,201605.0,56745.0,NUR,4795,NaN,A+
22,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,201608.0,89488.0,NUR,4069,NaN,A+
23,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,201608.0,94546.0,NSP,4614,NaN,A+
24,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,201701.0,22741.0,NUR,4634C,NaN,A+
25,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,201701.0,24245.0,NSP,4886,NaN,A+
26,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202108.0,94661.0,NGR,6152,NaN,A+
27,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202108.0,94669.0,NGR,6638,NaN,A+
28,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202201.0,18571.0,NGR,6733,NaN,A
29,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202201.0,23523.0,NGR,6002C,NaN,A-
30,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202205.0,57706.0,NGR,6803,NaN,A
31,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202205.0,58809.0,NGR,6064C,NaN,A+
32,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202208.0,89936.0,NGR,6893,NaN,A
33,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202208.0,89938.0,NGR,6172,NaN,A+
34,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202301.0,18133.0,NGR,6342,NaN,A+
35,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202301.0,24047.0,NGR,6207L,NaN,A+
36,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202301.0,25044.0,NGR,6207,NaN,A+
37,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202305.0,50541.0,NGR,6244,NaN,A
38,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202305.0,52622.0,NGR,6234,NaN,A+
39,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202305.0,53170.0,NGR,6244L,NaN,A+
40,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202401.0,14568.0,NGR,6301,NaN,A-
41,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202401.0,14571.0,NGR,6301L,NaN,A+
42,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202405.0,50399.0,NGR,6613,NaN,A+
43,794,SB,Second Baccalaureate,201508,UG,SA,PNR,Pre-Nursing,W,White,...,25,-,-,-,202405.0,54659.0,NGR,6613L,NaN,A+

,Pidm,Semester,Admit_Level,Admit_College,Lastest_Major,Trump_Race,Trump_Race_Desc,MULTI,Race,NEW_ETHNICITY,...,SAT-ERW,SATM,SAT_TOTAL,Final GPA,Semester GPA,Semester Grades,Semester Points,Classes,CRN,Converted_SAT
0,794,201508,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,4.00,"['A+', 'A+', 'A+']","[4.0, 4.0, 4.0]","['NUR3805', 'NUR3078', 'NUR4895']","[83267.0, 89943.0, 94441.0]",1210.0
1,794,201601,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,4.00,"['A+', 'A+']","[4.0, 4.0]","['NUR4828C', 'NUR4128']","[22277.0, 22671.0]",1210.0
2,794,201605,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,4.00,"['A+', 'A+']","[4.0, 4.0]","['NUR4169C', 'NUR4795']","[55333.0, 56745.0]",1210.0
3,794,201608,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,4.00,"['A+', 'A+']","[4.0, 4.0]","['NUR4069', 'NSP4614']","[89488.0, 94546.0]",1210.0
4,794,201701,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,4.00,"['A+', 'A+']","[4.0, 4.0]","['NUR4634C', 'NSP4886']","[22741.0, 24245.0]",1210.0
5,794,202108,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,4.00,"['A+', 'A+']","[4.0, 4.0]","['NGR6152', 'NGR6638']","[94661.0, 94669.0]",1210.0
6,794,202201,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,3.84,"['A', 'A-']","[4.0, 3.67]","['NGR6733', 'NGR6002C']","[18571.0, 23523.0]",1210.0
7,794,202205,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,4.00,"['A', 'A+']","[4.0, 4.0]","['NGR6803', 'NGR6064C']","[57706.0, 58809.0]",1210.0
8,794,202208,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,4.00,"['A', 'A+']","[4.0, 4.0]","['NGR6893', 'NGR6172']","[89936.0, 89938.0]",1210.0
9,794,202301,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,4.00,"['A+', 'A+', 'A+']","[4.0, 4.0, 4.0]","['NGR6342', 'NGR6207L', 'NGR6207']","[18133.0, 24047.0, 25044.0]",1210.0
10,794,202305,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,4.00,"['A', 'A+', 'A+']","[4.0, 4.0, 4.0]","['NGR6244', 'NGR6234', 'NGR6244L']","[50541.0, 52622.0, 53170.0]",1210.0
11,794,202401,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,3.84,"['A-', 'A+']","[3.67, 4.0]","['NGR6301', 'NGR6301L']","[14568.0, 14571.0]",1210.0
12,794,202405,UG,SA,Pre-Nursing,W,White,NaN,W White,Not Hispanic or Latino,...,NaN,NaN,NaN,3.98,4.00,"['A+', 'A+']","[4.0, 4.0]","['NGR6613', 'NGR6613L']","[50399.0, 54659.0]",1210.0

In [9]:
parsed['Semester Grades'] = parsed['Semester Grades'].apply(lambda x: ast.literal_eval(x))
parsed['Semester Points'] = parsed['Semester Points'].apply(lambda x: ast.literal_eval(x))
parsed['Classes'] = parsed['Classes'].apply(lambda x: ast.literal_eval(x))

In [10]:
data = parsed.groupby('Pidm').agg({
    "ACTE": 'first',
    "ACTR": 'first',
    "ACTS": 'first',
    "ACTM": 'first',
    "EACT": 'first',
    "SAT-ERW": 'first',
    "SATM": 'first',
    "SAT_TOTAL": 'first',
    "HS GPA": 'first',
    'Final GPA': 'first',
    'Semester GPA': lambda x: list(x),
    'Semester Grades': lambda x: sum(x, []),
    'Semester Points': lambda x: sum(x, []),
    'Classes': lambda x: sum(x, []),
}).reset_index()

data

,Pidm,ACTE,ACTR,ACTS,ACTM,EACT,SAT-ERW,SATM,SAT_TOTAL,HS GPA,Final GPA,Semester GPA,Semester Grades,Semester Points,Classes
0,794,25.0,25.0,22.0,26.0,25.0,NaN,NaN,NaN,3.30,3.98,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 3.84, 4.0, 4.0,...","[A+, A+, A+, A+, A+, A+, A+, A+, A+, A+, A+, A...","[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, ...","[NUR3805, NUR3078, NUR4895, NUR4828C, NUR4128,..."
1,1210,25.0,21.0,24.0,21.0,23.0,NaN,NaN,NaN,3.28,4.00,"[4.0, 4.0, 4.0, 4.0]","[A+, A+, A+, A, A, A, A, A+, A, A]","[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, ...","[ENG3674, HFT3894, ANT2000, HSC2100, LIT2000, ..."
2,1833,25.0,30.0,28.0,25.0,27.0,NaN,NaN,NaN,3.87,3.78,"[3.84, 3.84, 4.0, nan, 3.84, 3.5, 3.56, 4.0]","[A-, A, A, A-, A, A, W, A, A-, B, A, A, A+, B-...","[3.67, 4.0, 4.0, 3.67, 4.0, 4.0, 0.0, 4.0, 3.6...","[ANT2410, AST2002, BUL3320, LIT2000, FIN3403, ..."
3,3277,27.0,35.0,30.0,25.0,29.0,NaN,NaN,NaN,4.06,4.00,[4.0],"[A, A]","[4.0, 4.0]","[QMB3200, GEB4890]"
4,4998,15.0,14.0,16.0,18.0,16.0,NaN,NaN,NaN,0.00,3.89,"[3.67, 4.0, 4.0]","[A-, A, A]","[3.67, 4.0, 4.0]","[GEY4322, LAE4414, GEY4608]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86016,3984703,NaN,NaN,NaN,NaN,NaN,510.0,510.0,1020.0,3.64,3.50,[3.5],"[A-, B+]","[3.67, 3.33]","[SLS2901, THE2000]"
86017,3984725,NaN,NaN,NaN,NaN,NaN,580.0,590.0,1170.0,3.64,3.34,[3.34],"[B, A-]","[3.0, 3.67]","[HSC2000, SPC2608]"
86018,3984750,18.0,18.0,20.0,17.0,18.0,410.0,340.0,750.0,3.29,2.33,[2.33],[C+],[2.33],[MMC3602]
86019,3984772,NaN,NaN,NaN,NaN,NaN,450.0,480.0,930.0,0.00,0.00,[0.0],[F],[0.0],[HUM1020]
86020,3988409,NaN,NaN,NaN,NaN,NaN,560.0,560.0,1120.0,3.73,2.34,[2.34],"[B, C-]","[3.0, 1.67]","[PSY2012, THE2000]"

In [ ]:
act_to_sat_conversion_math = {
    "36": 800, "35": 780, "34": 760, '33': 740, "32": 720, "31": 710,
    "30": 700, "29": 680, "28": 660, "27": 640, '26': 610, "25": 590,
    "24": 580, "23": 560, "22": 540, '21': 530, "20": 520, '19': 510,
    "18": 500, "17": 470, '16': 430, "15": 400, "14": 330, "13": 330,
    "12": 310, "11": 280, "10": 260,
}

act_to_sat_conversion_eng = {
    "72": 790, '71': 770, '70': 750, '69': 740, '68': 730,
    '67': 720, '66': 710, '65': 700, '64': 700, '63': 690,
    "62": 680, '61': 680, '60': 670, '59': 660, '58': 660,
    '57': 650, '56': 640, '55': 640, '54': 630, '53': 630,
    '52': 620, '51': 610, '50': 610, '49': 600, '48': 590,
    "47": 580, '46': 580, '45': 570, '44': 560, '43': 550,
    "42": 540, '41': 540, '40': 530, '39': 520, '38': 510,
    '37': 500, '36': 500, '35': 490, '34': 480, '33': 470,
    '32': 460, '31': 450, '30': 440, '29': 430, '28': 420,
    "27": 410, '26': 400, '25': 390, '24': 380, '23': 370,
    '22': 360, '21': 350, '20': 340, '19': 330, '18': 320,
    '17': 310, '16': 300, '15': 290, '14': 280
}

# Convert ACTM to SATM and keep the highest SATM
def convert_actm_to_satm(row):
    actm = row['ACTM']
    satm = row['SATM']
    
    if actm != '-' and actm in act_to_sat_conversion_math:
        converted_satm = act_to_sat_conversion_math[actm]
        if satm == '-' or converted_satm > int(satm):
            return converted_satm
    return int(satm) if satm != '-' else '-'

# Sum ACTR and ACTE, compare with SAT-ERW, and keep the highest
def convert_actr_acte_to_saterw(row):
    actr, acte = row['ACTR'], row['ACTE']
    sat_erw = row['SAT-ERW']
    if pd.isna(sat_erw):
        sat_erw = '-'

    if actr != '-' and acte != '-' and actr in act_to_sat_conversion_eng and acte in act_to_sat_conversion_eng:
        converted_sum = act_to_sat_conversion_eng[str(int(actr)+int(acte))]
        if sat_erw == '-' or converted_sum > int(sat_erw):
            return converted_sum
    return int(sat_erw) if sat_erw != '-' else '-'

data['SATM'] = data.apply(convert_actm_to_satm, axis=1)
data['SAT-ERW'] = data.apply(convert_actr_acte_to_saterw, axis=1)

data = data[(data['SAT-ERW'] != '-') & (data['SATM'] != '-') & (data['HS GPA'].notnull())]
data = data.drop_duplicates(subset='Pidm')

print(Counter([letter for sublist in data['Semester Grades'] for letter in sublist]))

fail_grades = ['F', 'IF', 'C', 'C-', 'D+', 'D', 'D-']
data['Fail'] = data['Semester Grades'].apply(lambda grades: any(grade in fail_grades for grade in grades)).astype(int)

data

Counter({'A': 743747, 'B': 326658, 'A+': 269699, 'A-': 219129, 'B+': 153844, 'C': 141757, 'B-': 96440, 'S': 78561, 'C+': 66537, 'F': 63140, 'W': 54061, 'D': 30935, 'C-': 29791, 'WC': 21348, 'D+': 11896, 'D-': 6852, 'U': 5086, 'F*': 2178, 'WE': 1945, 'CF': 1894, 'IF': 1699, 'C*': 1030, 'Z': 817, 'B*': 765, 'D*': 568, 'A*': 410, 'B-*': 404, 'C-*': 385, 'C+*': 356, 'FF': 331, 'B+*': 240, 'A-*': 236, 'CM': 208, 'I': 197, 'D+*': 188, 'D-*': 177, 'S*': 81, 'CB': 76, 'CA': 76, 'A+*': 70, 'CC': 55, 'IU': 51, 'CD': 49, 'IF*': 48, 'CB-': 32, '-': 32, 'CC-': 31, 'CB+': 30, 'CA-': 27, 'CD-': 23, 'CU': 23, 'W*': 23, 'N': 21, 'CC+': 21, 'CD+': 13, 'Z*': 11, 'M': 10, 'CS': 8, 'CA+': 8, 'U*': 3, 'CW': 3, 'C-#': 2, 'D#': 2, 'F#': 2, 'MU': 2, 'IB': 2, 'CIF': 1, 'B+#': 1, 'B#': 1, 'A#': 1, 'CI': 1, 'ID': 1, 'IU*': 1, 'IS': 1})

,Pidm,ACTE,ACTR,ACTS,ACTM,EACT,SAT-ERW,SATM,SAT_TOTAL,HS GPA,Final GPA,Semester GPA,Semester Grades,Semester Points,Classes,Fail
0,794,25.0,25.0,22.0,26.0,25.0,NaN,NaN,NaN,3.30,3.98,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 3.84, 4.0, 4.0,...","[A+, A+, A+, A+, A+, A+, A+, A+, A+, A+, A+, A...","[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, ...","[NUR3805, NUR3078, NUR4895, NUR4828C, NUR4128,...",0
1,1210,25.0,21.0,24.0,21.0,23.0,NaN,NaN,NaN,3.28,4.00,"[4.0, 4.0, 4.0, 4.0]","[A+, A+, A+, A, A, A, A, A+, A, A]","[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, ...","[ENG3674, HFT3894, ANT2000, HSC2100, LIT2000, ...",0
2,1833,25.0,30.0,28.0,25.0,27.0,NaN,NaN,NaN,3.87,3.78,"[3.84, 3.84, 4.0, nan, 3.84, 3.5, 3.56, 4.0]","[A-, A, A, A-, A, A, W, A, A-, B, A, A, A+, B-...","[3.67, 4.0, 4.0, 3.67, 4.0, 4.0, 0.0, 4.0, 3.6...","[ANT2410, AST2002, BUL3320, LIT2000, FIN3403, ...",0
3,3277,27.0,35.0,30.0,25.0,29.0,NaN,NaN,NaN,4.06,4.00,[4.0],"[A, A]","[4.0, 4.0]","[QMB3200, GEB4890]",0
4,4998,15.0,14.0,16.0,18.0,16.0,NaN,NaN,NaN,0.00,3.89,"[3.67, 4.0, 4.0]","[A-, A, A]","[3.67, 4.0, 4.0]","[GEY4322, LAE4414, GEY4608]",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86016,3984703,NaN,NaN,NaN,NaN,NaN,510.0,510.0,1020.0,3.64,3.50,[3.5],"[A-, B+]","[3.67, 3.33]","[SLS2901, THE2000]",0
86017,3984725,NaN,NaN,NaN,NaN,NaN,580.0,590.0,1170.0,3.64,3.34,[3.34],"[B, A-]","[3.0, 3.67]","[HSC2000, SPC2608]",0
86018,3984750,18.0,18.0,20.0,17.0,18.0,410.0,340.0,750.0,3.29,2.33,[2.33],[C+],[2.33],[MMC3602],0
86019,3984772,NaN,NaN,NaN,NaN,NaN,450.0,480.0,930.0,0.00,0.00,[0.0],[F],[0.0],[HUM1020],1
86020,3988409,NaN,NaN,NaN,NaN,NaN,560.0,560.0,1120.0,3.73,2.34,[2.34],"[B, C-]","[3.0, 1.67]","[PSY2012, THE2000]",1

In [ ]:
X = data[['SAT-ERW', 'SATM', 'HS GPA']]
y = data['Fail']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

print(data['Fail'].value_counts())

Fail
1    54983
0    30980
Name: count, dtype: int64

In [35]:
model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{cm}')

Accuracy: 0.6506717850287908
Confusion Matrix:
[[1975 4206]
 [1800 9212]]