In [20]:
import pandas as pd

student_data = pd.read_csv("studentData.csv")
grades = pd.read_csv("parsed_grades.csv")

C:\Users\judem\AppData\Local\Temp\ipykernel_16912\370795989.py:3: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  student_data = pd.read_csv("studentData.csv")

In [24]:
#Add Numeric GPA Column

grade_mapping = dict(grades[['Code', 'Quality Points']].values)

student_data = student_data.drop(student_data[student_data.FINAL_GRADE == 'W'].index)
student_data['numeric_gpa'] = student_data.FINAL_GRADE.map(grade_mapping)
student_data['numeric_gpa'] = student_data['numeric_gpa'].astype(float)

student_data.head()

,Pidm,Admit_Code,Admit_Desc,Admit_Term,Admit_Level,Admit_College,Admit_Major_Code,Major_Desc,Trump_Race,Trump_Race_Desc,...,SAT-ERW,SATM,SAT_TOTAL,Term,CRN,SUBJ,CRSE_NUMB,REPEAT_IND,FINAL_GRADE,numeric_gpa
0,285,FS,Former USF Student Returning,202101,UG,SA,BGS,General Studies,W,White,...,-,-,-,202101.0,10803.0,LIS,3361,NaN,A,4.00
1,285,FS,Former USF Student Returning,202101,UG,SA,BGS,General Studies,W,White,...,-,-,-,202101.0,16614.0,LIS,3353,NaN,A-,3.67
2,285,FS,Former USF Student Returning,202101,UG,SA,BGS,General Studies,W,White,...,-,-,-,202101.0,24972.0,COP,2030,NaN,B+,3.33
3,285,FS,Former USF Student Returning,202101,UG,SA,BGS,General Studies,W,White,...,-,-,-,202101.0,26205.0,CIS,4510,NaN,A,4.00
5,432,FS,Former USF Student Returning,201908,UG,SA,BGS,General Studies,B,Black or African American,...,-,-,-,201908.0,82811.0,MUS,4930,NaN,IF,0.00

In [25]:
#Final and Semester GPAs (Assuming all classes are equal credits)

student_final_gpa = student_data.groupby('Pidm')['numeric_gpa'].mean().reset_index()

student_semester_gpa = student_data.groupby(['Pidm', 'Term'])['numeric_gpa'].mean().reset_index()


print(student_final_gpa)
print(student_semester_gpa)

           Pidm  numeric_gpa
0           285     3.750000
1           432     0.000000
2           705     4.000000
3           794     3.977241
4          1089     4.000000
...         ...          ...
103874  3991351          NaN
103875  3991376          NaN
103876  3991590          NaN
103877  3991850          NaN
103878  3992464          NaN

[103879 rows x 2 columns]
           Pidm      Term  numeric_gpa
0           285  202101.0        3.750
1           432  201908.0        0.000
2           705  202208.0        4.000
3           794  201508.0        4.000
4           794  201601.0        4.000
...         ...       ...          ...
669130  3984703  202405.0        3.500
669131  3984725  202405.0        3.335
669132  3984750  202405.0        2.330
669133  3984772  202405.0        0.000
669134  3988409  202405.0        2.335

[669135 rows x 3 columns]

In [26]:
#Student Classes per Semester (As an array of strings)

student_data['class'] = student_data['SUBJ'] + student_data['CRSE_NUMB']
student_data['class'] = student_data['class'].astype(str)
semester_classes = student_data.groupby(['Pidm', 'Term'])['class'].apply(list).reset_index()

print(semester_classes)

           Pidm      Term                                              class
0           285  202101.0               [LIS3361, LIS3353, COP2030, CIS4510]
1           432  201908.0                        [MUS4930, CCJ3117, IDS4934]
2           705  202208.0  [MCB2000, MCB2000L, HUN2201, BSC2085, BSC2085L...
3           794  201508.0                        [NUR3805, NUR3078, NUR4895]
4           794  201601.0                                [NUR4828C, NUR4128]
...         ...       ...                                                ...
669130  3984703  202405.0                                 [SLS2901, THE2000]
669131  3984725  202405.0                                 [HSC2000, SPC2608]
669132  3984750  202405.0                                          [MMC3602]
669133  3984772  202405.0                                          [HUM1020]
669134  3988409  202405.0                                 [PSY2012, THE2000]

[669135 rows x 3 columns]

In [27]:
student_gpa_map = dict(student_final_gpa[['Pidm', 'numeric_gpa']].values)
student_data['Final GPA'] = student_data.Pidm.map(student_gpa_map)

student_data.drop(['CRN', 'SUBJ', 'CRSE_NUMB', 'REPEAT_IND', 'FINAL_GRADE', 'numeric_gpa', 'class'], axis=1, inplace=True)
student_data.rename(columns={'Final_GPA':'HS GPA', 'Term':'Semester'}, inplace=True)
student_data.head()

,Pidm,Admit_Code,Admit_Desc,Admit_Term,Admit_Level,Admit_College,Admit_Major_Code,Major_Desc,Trump_Race,Trump_Race_Desc,...,ACTE,ACTM,ACTR,ACTS,EACT,SAT-ERW,SATM,SAT_TOTAL,Semester,Final GPA
0,285,FS,Former USF Student Returning,202101,UG,SA,BGS,General Studies,W,White,...,-,-,-,-,-,-,-,-,202101.0,3.75
1,285,FS,Former USF Student Returning,202101,UG,SA,BGS,General Studies,W,White,...,-,-,-,-,-,-,-,-,202101.0,3.75
2,285,FS,Former USF Student Returning,202101,UG,SA,BGS,General Studies,W,White,...,-,-,-,-,-,-,-,-,202101.0,3.75
3,285,FS,Former USF Student Returning,202101,UG,SA,BGS,General Studies,W,White,...,-,-,-,-,-,-,-,-,202101.0,3.75
5,432,FS,Former USF Student Returning,201908,UG,SA,BGS,General Studies,B,Black or African American,...,-,-,-,-,-,-,-,-,201908.0,0.00

In [28]:
student_data = student_data.groupby(['Pidm', 'Admit_Code', 'Admit_Desc', 'Admit_Term', 'Admit_College', 'Admit_Major_Code', 'Major_Desc', 'MULTI', 'Race', 'NEW_ETHNICITY', 'GENDER_Code', 'GENDER', 'CITZ_IND', 'CITZ_CODE', 'CITZ_DESC', 'HS GPA', 'ACTE', 'ACTM', 'ACTR', 'ACTS', 'EACT', 'SAT-ERW', 'SATM', 'SAT_TOTAL', 'Semester', 'Final GPA']).size().reset_index(name='count')
student_data.drop(['count'], axis=1, inplace=True)
student_data['Semester GPA'] = student_semester_gpa['numeric_gpa']
student_data['Classes'] = semester_classes['class']

student_data.head()

,Pidm,Admit_Code,Admit_Desc,Admit_Term,Admit_College,Admit_Major_Code,Major_Desc,MULTI,Race,NEW_ETHNICITY,...,ACTR,ACTS,EACT,SAT-ERW,SATM,SAT_TOTAL,Semester,Final GPA,Semester GPA,Classes
0,3963,FS,Former USF Student Returning,201508,SP,FIN,Finance,Multi-Race,B Black or African American\nW White,Not Hispanic or Latino,...,-,-,-,-,-,-,201508.0,4.000,3.75,"[LIS3361, LIS3353, COP2030, CIS4510]"
1,15670,FS,Former USF Student Returning,202201,US,BGS,General Studies,Multi-Race,B Black or African American\nW White,Not Hispanic or Latino,...,21,20,21,-,-,-,202201.0,4.000,0.00,"[MUS4930, CCJ3117, IDS4934]"
2,351891,SB,Second Baccalaureate,201601,SA,ISS,Interdisciplinary Social Sci,Multi-Race,B Black or African American\nW White,Hispanic or Latino,...,34,20,24,360,570,930,201601.0,2.066,4.00,"[MCB2000, MCB2000L, HUN2201, BSC2085, BSC2085L..."
3,351891,SB,Second Baccalaureate,201601,SA,ISS,Interdisciplinary Social Sci,Multi-Race,B Black or African American\nW White,Hispanic or Latino,...,34,20,24,360,570,930,201608.0,2.066,4.00,"[NUR3805, NUR3078, NUR4895]"
4,676559,FS,Former USF Student Returning,201805,SA,BGS,General Studies,Multi-Race,I American Indian or Alaska Native\nW White,Not Hispanic or Latino,...,24,24,27,350,760,1110,201805.0,3.670,4.00,"[NUR4828C, NUR4128]"

In [29]:
student_data = student_data.astype(str)
student_data['Pidm'] = student_data['Pidm'].astype(int)
student_data['Final GPA'] = student_data['Final GPA'].astype(float)
student_data['Semester'] = student_data['Semester'].astype(float)
student_data['Semester'] = student_data['Semester'].round(0)
student_data['Semester'] = student_data['Semester'].astype(str)







print(student_data)

          Pidm Admit_Code                    Admit_Desc Admit_Term  \
0         3963         FS  Former USF Student Returning     201508
1        15670         FS  Former USF Student Returning     202201
2       351891         SB          Second Baccalaureate     201601
3       351891         SB          Second Baccalaureate     201601
4       676559         FS  Former USF Student Returning     201805
...        ...        ...                           ...        ...
34732  3970631         BL  Beginner(FTIC) - Lower Level     202405
34733  3971554         BL  Beginner(FTIC) - Lower Level     202405
34734  3972828         BL  Beginner(FTIC) - Lower Level     202405
34735  3974947         BL  Beginner(FTIC) - Lower Level     202405
34736  3976542         BL  Beginner(FTIC) - Lower Level     202405

      Admit_College Admit_Major_Code                    Major_Desc  \
0                SP              FIN                       Finance
1                US              BGS               General Studies
2                SA              ISS  Interdisciplinary Social Sci
3                SA              ISS  Interdisciplinary Social Sci
4                SA              BGS               General Studies
...             ...              ...                           ...
34732            PH              HSS               Health Sciences
34733            AC              SOC                     Sociology
34734            AC              BMS           Biomedical Sciences
34735            PH              HSS               Health Sciences
34736            AC              PPS   Professional Sciences (Pre)

            MULTI                                         Race  \
0      Multi-Race         B Black or African American\nW White
1      Multi-Race         B Black or African American\nW White
2      Multi-Race         B Black or African American\nW White
3      Multi-Race         B Black or African American\nW White
4      Multi-Race  I American Indian or Alaska Native\nW White
...           ...                                          ...
34732  Multi-Race         B Black or African American\nW White
34733  Multi-Race                             A Asian\nW White
34734  Multi-Race         A Asian\nB Black or African American
34735  Multi-Race  I American Indian or Alaska Native\nW White
34736  Multi-Race         B Black or African American\nW White

                NEW_ETHNICITY  ... ACTR ACTS EACT SAT-ERW SATM SAT_TOTAL  \
0      Not Hispanic or Latino  ...    -    -    -       -    -         -
1      Not Hispanic or Latino  ...   21   20   21       -    -         -
2          Hispanic or Latino  ...   34   20   24     360  570       930
3          Hispanic or Latino  ...   34   20   24     360  570       930
4      Not Hispanic or Latino  ...   24   24   27     350  760      1110
...                       ...  ...  ...  ...  ...     ...  ...       ...
34732  Not Hispanic or Latino  ...    -    -    -     610  580      1190
34733  Not Hispanic or Latino  ...   29   25   27     690  630      1320
34734  Not Hispanic or Latino  ...    -    -    -     710  660      1370
34735  Not Hispanic or Latino  ...    -    -    -     610  520      1130
34736      Hispanic or Latino  ...    -    -    -     530  550      1080

       Semester Final GPA        Semester GPA  \
0      201508.0     4.000                3.75
1      202201.0     4.000                 0.0
2      201601.0     2.066                 4.0
3      201608.0     2.066                 4.0
4      201805.0     3.670                 4.0
...         ...       ...                 ...
34732  202405.0     4.000                2.11
34733  202405.0     2.000               3.335
34734  202405.0     3.165                3.11
34735  202405.0     3.000  1.8866666666666667
34736  202405.0     4.000                 2.8

                                                 Classes
0           ['LIS3361', 'LIS3353', 'COP2030', 'CIS4510']
1                      ['MUS4930', 'CCJ3117', 'IDS4934']
2      ['MCB2000', 'MCB2000L', 'HUN2201', 'BSC2085', ...
3                      ['NUR3805', 'NUR3078', 'NUR4895']
4                                ['NUR4828C', 'NUR4128']
...                                                  ...
34732                  ['CCJ3701', 'REL3936', 'CPO2002']
34733                             ['SPN1120', 'REL3191']
34734                  ['SPN1121', 'ISS3010', 'REL3040']
34735  ['ISS4935', 'PEM2131', 'AFA4931', 'STA2122', '...
34736  ['STA2122', 'REL3900', 'WST3015', 'AFS2250', '...

[34737 rows x 28 columns]

In [30]:
student_data.to_csv('new_table.csv')